# DSH Web system-tray app (generated by dsh-tray-launcher).
# Runs with NO visible window: it starts the dsh web server hidden, then shows a
# small whale icon in the notification area (like the Bluetooth icon).
#   - double-click / "Open Web UI" : opens the configured Web GUI URL
#   - "Stop DSH Web service"       : stops the dsh web node process
#   - "Exit"                       : closes the DSH browser tab(s) - and the
#                                     window too if the tab was the only one -
#                                     then stops the server and removes the icon
#
# Paths and settings are substituted at install time by the
# dsh-tray-launcher host plugin.

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$iconPath = Join-Path $PSScriptRoot 'DeepSeekHarness-WhaleGirl.ico'
$node     = {{NODE}}
$bin      = {{BIN}}
$url      = {{URL}}
$profile  = {{PROFILE}}
$logDir   = $PSScriptRoot
$script:tokenUrl = $url
$script:controlPath = Join-Path $PSScriptRoot 'tray-control.json'

# DSH home: honour $DSH_HOME, else the platform default (~/.dsh).
$dshHome = if ($env:DSH_HOME -and $env:DSH_HOME.Trim() -ne '') { $env:DSH_HOME } else { Join-Path $env:USERPROFILE '.dsh' }

# Browser control via DevTools protocol. We launch a Chromium browser with a
# dedicated profile + --remote-debugging-port so we can later close the exact DSH
# tab. Falling back to the default browser is possible but gives no tab control.
$script:cdpPort    = 9223
$script:dshProfile = Join-Path $dshHome 'dsh-browser-profile'
$script:browserExe = $null
foreach ($_p in @(
      "$env:ProgramFiles\Microsoft\Edge\Application\msedge.exe",
      "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe",
      "$env:ProgramFiles\Google\Chrome\Application\chrome.exe",
      "${env:ProgramFiles(x86)}\Google\Chrome\Application\chrome.exe")) {
    if (Test-Path $_p) { $script:browserExe = $_p; break }
}

function Stop-DshWeb {
    Get-CimInstance Win32_Process -Filter "Name='node.exe'" |
        Where-Object { $_.CommandLine -like '*@deepseek-ai\dsh\lib\bin.js*' -and $_.CommandLine -like "*--profile $profile*" } |
        ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
}

function Get-DshWeb {
    Get-CimInstance Win32_Process -Filter "Name='node.exe'" |
        Where-Object { $_.CommandLine -like '*@deepseek-ai\dsh\lib\bin.js*' -and $_.CommandLine -like "*--profile $profile*" }
}

function Start-DshWeb {
    if ($bin -and (Test-Path $bin)) {
        # Preferred: launch the exact node + dsh bin used to install this launcher
        # (no PATH dependency, exact version control).
        if (-not (Test-Path $node)) { return $false }
        $args = @($bin, '--profile', $profile, '--no-open')
        Start-Process -FilePath $node -ArgumentList $args -WindowStyle Hidden `
            -RedirectStandardOutput "$logDir\dsh-web.out.log" `
            -RedirectStandardError  "$logDir\dsh-web.err.log" | Out-Null
        return $true
    }
    # Fallback: rely on `dsh` being on PATH.
    try {
        $dsh = (Get-Command dsh -ErrorAction Stop).Source
        Start-Process -FilePath $dsh -ArgumentList @('--profile', $profile, '--no-open') -WindowStyle Hidden | Out-Null
        return $true
    } catch {
        return $false
    }
}

function Start-TrayLauncher {
    $vbs = Join-Path $PSScriptRoot 'start-dsh-tray.vbs'
    $wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
    if (-not (Test-Path $vbs)) { return $false }
    if (-not (Test-Path $wscript)) { return $false }
    Start-Process -FilePath $wscript -ArgumentList @('"' + $vbs + '"') -WindowStyle Hidden | Out-Null
    return $true
}

function Wait-DshReady {
    for ($i = 0; $i -lt 40; $i++) {
        try {
            $r = Invoke-WebRequest -Uri "$url/" -UseBasicParsing -TimeoutSec 3
            if ([int]$r.StatusCode -ne 404) { return $true }
        } catch {
            if ($_.Exception.Response -and ([int]$_.Exception.Response.StatusCode -ne 404)) { return $true }
        }
        Start-Sleep -Seconds 1
    }
    return $false
}

# Open the Web UI. Prefer a Chromium browser launched with a dedicated profile and
# a DevTools port (so Exit can close the tab); otherwise fall back to the default
# browser (best effort, no tab control).
function Open-DshUi {
    if ($script:browserExe -and (Test-Path $script:browserExe)) {
        Start-Process -FilePath $script:browserExe -ArgumentList @(
            "--remote-debugging-port=$($script:cdpPort)",
            "--user-data-dir=$($script:dshProfile)",
            "--no-first-run", "--no-default-browser-check",
            "--new-window", "$($script:tokenUrl)") | Out-Null
    } else {
        Start-Process -FilePath $script:tokenUrl | Out-Null
    }
}

# Close the DSH browser tab(s) via DevTools. Closing the only tab in a window
# closes that window too (normal browser behaviour). Only DSH targets are touched,
# never other tabs or the whole browser.
function Close-DshBrowserTabs {
    try {
        $tabs = Invoke-RestMethod -Uri "http://127.0.0.1:$($script:cdpPort)/json" -TimeoutSec 5
        $dshtabs = $tabs | Where-Object { $_.type -eq 'page' -and $_.url -like "*$url*" }
        foreach ($t in $dshtabs) {
            try { Invoke-RestMethod -Uri "http://127.0.0.1:$($script:cdpPort)/json/close/$($t.id)" -TimeoutSec 5 | Out-Null } catch { }
        }
    } catch { }
}

function Invoke-ExitFlow {
    param([switch]$Restart)
    $script:notifyIcon.Visible = $false
    Close-DshBrowserTabs
    Stop-DshWeb
    if ($Restart) {
        [void](Start-TrayLauncher)
    }
    [System.Windows.Forms.Application]::Exit()
}

function Consume-ControlCommand {
    if (-not (Test-Path $script:controlPath)) { return }
    try {
        $raw = Get-Content $script:controlPath -Raw -ErrorAction Stop
        Remove-Item $script:controlPath -Force -ErrorAction SilentlyContinue
        $action = $null
        try {
            $payload = $raw | ConvertFrom-Json -ErrorAction Stop
            if ($payload.action) { $action = [string]$payload.action }
        } catch {
            $action = [string]$raw
        }
        if (-not $action) { return }
        switch ($action.ToLowerInvariant()) {
            'exit' { Invoke-ExitFlow; return }
            'restart' { Invoke-ExitFlow -Restart; return }
            'open' { Open-DshUi; return }
            default { return }
        }
    } catch { }
}

# Make sure the server is running (start it hidden if not already).
if (-not (Get-DshWeb)) { [void](Start-DshWeb) }
$ready = Wait-DshReady

# Extract the authenticated URL from the dsh output log. The server prints a
# one-time token in the URL (e.g. http://127.0.0.1:3080/?token=...). Without it
# the browser gets "dsh web authentication required".
if ($ready) {
    try {
        $logContent = Get-Content "$logDir\dsh-web.out.log" -Raw -ErrorAction SilentlyContinue
        if ($logContent -match 'dsh web: (http://[^\s]+)') {
            $script:tokenUrl = $Matches[1]
        }
    } catch { }
}

# Double-clicking the desktop icon should open the Web UI automatically.
if ($ready) { Open-DshUi }

# Build the tray icon.
$icon = New-Object System.Drawing.Icon($iconPath)
$script:notifyIcon = New-Object System.Windows.Forms.NotifyIcon
$script:notifyIcon.Icon = $icon
$script:notifyIcon.Text = "DSH Web"
$script:notifyIcon.Visible = $true

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$mOpen = New-Object System.Windows.Forms.ToolStripMenuItem("Open Web UI")
$mRestart = New-Object System.Windows.Forms.ToolStripMenuItem("Restart DSH Web service")
$mStop = New-Object System.Windows.Forms.ToolStripMenuItem("Stop DSH Web service")
$mQuit = New-Object System.Windows.Forms.ToolStripMenuItem("Exit")
$null = $mOpen.Add_Click({ Open-DshUi })
$null = $mRestart.Add_Click({ Invoke-ExitFlow -Restart })
$null = $mStop.Add_Click({ Stop-DshWeb; $script:notifyIcon.ShowBalloonTip(2000, "DSH Web", "Service stopped.", [System.Windows.Forms.ToolTipIcon]::Info) })
$null = $mQuit.Add_Click({ Invoke-ExitFlow })
$null = $menu.Items.Add($mOpen)
$null = $menu.Items.Add($mRestart)
$null = $menu.Items.Add($mStop)
$null = $menu.Items.Add((New-Object System.Windows.Forms.ToolStripSeparator))
$null = $menu.Items.Add($mQuit)
$script:notifyIcon.ContextMenuStrip = $menu
$null = $script:notifyIcon.Add_DoubleClick({ Open-DshUi })

$script:controlTimer = New-Object System.Windows.Forms.Timer
$script:controlTimer.Interval = 1000
$null = $script:controlTimer.Add_Tick({ Consume-ControlCommand })
$script:controlTimer.Start()

if ($ready) {
    $script:notifyIcon.ShowBalloonTip(3000, "DSH Web", "Service ready. Web UI opened.", [System.Windows.Forms.ToolTipIcon]::Info)
} else {
    $script:notifyIcon.ShowBalloonTip(3000, "DSH Web", "Server did not become ready. Check logs.", [System.Windows.Forms.ToolTipIcon]::Warning)
}

[System.Windows.Forms.Application]::Run()

# Clean up after Exit.
$script:controlTimer.Stop()
$script:controlTimer.Dispose()
$script:notifyIcon.Dispose()
$icon.Dispose()
